### ISSUE TITLE
Feature tracking issue: fopen

### ISSUE THREAD

**Issue by pi-pi3** [pi-pi3/ext2-rs#1]
This issue is for tracking progress of the feature `fopen`.

 - [ ] ~~`sys::directory::Directory` for internal operations on a directory.~~ **edit:** not appropriate
 - [x] an abstract, safe `Directory` type.
 - [x] finding an inode by directory walking.

**Comment by pi-pi3** [comment]
bebfa33 implements the `Directory` iterator.

**Comment by pi-pi3** [comment]
"Opening" an inode is now possible with `Synced<Ext2>::find_inode`.
