### ISSUE TITLE
 Feature tracking issue: fread

### ISSUE THREAD

**Issue by pi-pi3** [pi-pi3/ext2-rs#2]
This issue is for tracking progress of the feature `fread`.

 - [x] `sys::inode::Inode` for internal operations on an inode.
 - [x] safe, abstract `Inode` type
 - [x] correctly reading all blocks of an inode into a (user-)predefined buffer

**Comment by pi-pi3** [comment]
Reading whole contents of arbitrary inodes has been tested.
